// Code generated by github.com/nezhahq/agent/model/gen. DO NOT EDIT.

package model

import "errors"

func (c *AgentConfig) Apply(field string, v *AgentConfig) error {
	switch field {
	case "debug":
		c.Debug = v.Debug
	case "server":
		c.Server = v.Server
	case "client_secret":
		c.ClientSecret = v.ClientSecret
	case "uuid":
		c.UUID = v.UUID
	case "hard_drive_partition_allowlist":
		c.HardDrivePartitionAllowlist = v.HardDrivePartitionAllowlist
	case "nic_allowlist":
		c.NICAllowlist = v.NICAllowlist
	case "dns":
		c.DNS = v.DNS
	case "gpu":
		c.GPU = v.GPU
	case "temperature":
		c.Temperature = v.Temperature
	case "skip_connection_count":
		c.SkipConnectionCount = v.SkipConnectionCount
	case "skip_procs_count":
		c.SkipProcsCount = v.SkipProcsCount
	case "disable_auto_update":
		c.DisableAutoUpdate = v.DisableAutoUpdate
	case "disable_force_update":
		c.DisableForceUpdate = v.DisableForceUpdate
	case "disable_command_execute":
		c.DisableCommandExecute = v.DisableCommandExecute
	case "report_delay":
		c.ReportDelay = v.ReportDelay
	case "tls":
		c.TLS = v.TLS
	case "insecure_tls":
		c.InsecureTLS = v.InsecureTLS
	case "use_ipv6_country_code":
		c.UseIPv6CountryCode = v.UseIPv6CountryCode
	case "use_gitee_to_upgrade":
		c.UseGiteeToUpgrade = v.UseGiteeToUpgrade
	case "disable_nat":
		c.DisableNat = v.DisableNat
	case "disable_send_query":
		c.DisableSendQuery = v.DisableSendQuery
	case "ip_report_period":
		c.IPReportPeriod = v.IPReportPeriod
	case "self_update_period":
		c.SelfUpdatePeriod = v.SelfUpdatePeriod
	case "custom_ip_api":
		c.CustomIPApi = v.CustomIPApi
	default:
		return errors.New("field name is not valid")
	}
	return nil
}
