before:
  hooks:
    - go mod tidy -v
builds:
  - id: universal
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.arch={{.Arch}}
    goos:
      - linux
      - windows
      - freebsd
    goarch:
      - arm
      - arm64
      - 386
      - amd64
      - mips
      - mipsle
      - s390x
      - riscv64
    gomips:
      - softfloat
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    main: ./cmd/agent
    binary: nezha-agent
  - id: darwin-amd64
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.arch={{.Arch}}
    goos:
      - darwin
    goarch:
      - amd64
    main: ./cmd/agent
    binary: nezha-agent
  - id: darwin-arm64
    env:
      - CGO_ENABLED=1
      - CC=oa64-clang
      - CXX=oa64-clang++
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.arch={{.Arch}}
    goos:
      - darwin
    goarch:
      - arm64
    main: ./cmd/agent
    binary: nezha-agent
universal_binaries:
  - name_template: "nezha-agent"
    replace: false
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "nezha-agent"
archives:
  - name_template: "nezha-agent_{{ .Os }}_{{ .Arch }}"
    format: zip
    files:
      - none*
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore"
      - Merge pull request
      - Merge branch
      - go mod tidy
      - New translations
